/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZycieCodzienneRouteImport } from './routes/zycie-codzienne'
import { Route as TerapieRouteImport } from './routes/terapie'
import { Route as SpolecznoscRouteImport } from './routes/spolecznosc'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrawoFinanseRouteImport } from './routes/prawo-finanse'
import { Route as PomocKryzysowaRouteImport } from './routes/pomoc-kryzysowa'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as EtapyZyciaRouteImport } from './routes/etapy-zycia'
import { Route as BazaWiedzyRouteImport } from './routes/baza-wiedzy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtykulSlugRouteImport } from './routes/artykul.$slug'

const ZycieCodzienneRoute = ZycieCodzienneRouteImport.update({
  id: '/zycie-codzienne',
  path: '/zycie-codzienne',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapieRoute = TerapieRouteImport.update({
  id: '/terapie',
  path: '/terapie',
  getParentRoute: () => rootRouteImport,
} as any)
const SpolecznoscRoute = SpolecznoscRouteImport.update({
  id: '/spolecznosc',
  path: '/spolecznosc',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoFinanseRoute = PrawoFinanseRouteImport.update({
  id: '/prawo-finanse',
  path: '/prawo-finanse',
  getParentRoute: () => rootRouteImport,
} as any)
const PomocKryzysowaRoute = PomocKryzysowaRouteImport.update({
  id: '/pomoc-kryzysowa',
  path: '/pomoc-kryzysowa',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const EtapyZyciaRoute = EtapyZyciaRouteImport.update({
  id: '/etapy-zycia',
  path: '/etapy-zycia',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaWiedzyRoute = BazaWiedzyRouteImport.update({
  id: '/baza-wiedzy',
  path: '/baza-wiedzy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtykulSlugRoute = ArtykulSlugRouteImport.update({
  id: '/artykul/$slug',
  path: '/artykul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/etapy-zycia': typeof EtapyZyciaRoute
  '/kalkulator': typeof KalkulatorRoute
  '/katalog': typeof KatalogRoute
  '/konto': typeof KontoRoute
  '/pomoc-kryzysowa': typeof PomocKryzysowaRoute
  '/prawo-finanse': typeof PrawoFinanseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/spolecznosc': typeof SpolecznoscRoute
  '/terapie': typeof TerapieRoute
  '/zycie-codzienne': typeof ZycieCodzienneRoute
  '/artykul/$slug': typeof ArtykulSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/etapy-zycia': typeof EtapyZyciaRoute
  '/kalkulator': typeof KalkulatorRoute
  '/katalog': typeof KatalogRoute
  '/konto': typeof KontoRoute
  '/pomoc-kryzysowa': typeof PomocKryzysowaRoute
  '/prawo-finanse': typeof PrawoFinanseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/spolecznosc': typeof SpolecznoscRoute
  '/terapie': typeof TerapieRoute
  '/zycie-codzienne': typeof ZycieCodzienneRoute
  '/artykul/$slug': typeof ArtykulSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/etapy-zycia': typeof EtapyZyciaRoute
  '/kalkulator': typeof KalkulatorRoute
  '/katalog': typeof KatalogRoute
  '/konto': typeof KontoRoute
  '/pomoc-kryzysowa': typeof PomocKryzysowaRoute
  '/prawo-finanse': typeof PrawoFinanseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slownik': typeof SlownikRoute
  '/spolecznosc': typeof SpolecznoscRoute
  '/terapie': typeof TerapieRoute
  '/zycie-codzienne': typeof ZycieCodzienneRoute
  '/artykul/$slug': typeof ArtykulSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baza-wiedzy'
    | '/etapy-zycia'
    | '/kalkulator'
    | '/katalog'
    | '/konto'
    | '/pomoc-kryzysowa'
    | '/prawo-finanse'
    | '/sitemap.xml'
    | '/slownik'
    | '/spolecznosc'
    | '/terapie'
    | '/zycie-codzienne'
    | '/artykul/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/baza-wiedzy'
    | '/etapy-zycia'
    | '/kalkulator'
    | '/katalog'
    | '/konto'
    | '/pomoc-kryzysowa'
    | '/prawo-finanse'
    | '/sitemap.xml'
    | '/slownik'
    | '/spolecznosc'
    | '/terapie'
    | '/zycie-codzienne'
    | '/artykul/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/baza-wiedzy'
    | '/etapy-zycia'
    | '/kalkulator'
    | '/katalog'
    | '/konto'
    | '/pomoc-kryzysowa'
    | '/prawo-finanse'
    | '/sitemap.xml'
    | '/slownik'
    | '/spolecznosc'
    | '/terapie'
    | '/zycie-codzienne'
    | '/artykul/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BazaWiedzyRoute: typeof BazaWiedzyRoute
  EtapyZyciaRoute: typeof EtapyZyciaRoute
  KalkulatorRoute: typeof KalkulatorRoute
  KatalogRoute: typeof KatalogRoute
  KontoRoute: typeof KontoRoute
  PomocKryzysowaRoute: typeof PomocKryzysowaRoute
  PrawoFinanseRoute: typeof PrawoFinanseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlownikRoute: typeof SlownikRoute
  SpolecznoscRoute: typeof SpolecznoscRoute
  TerapieRoute: typeof TerapieRoute
  ZycieCodzienneRoute: typeof ZycieCodzienneRoute
  ArtykulSlugRoute: typeof ArtykulSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zycie-codzienne': {
      id: '/zycie-codzienne'
      path: '/zycie-codzienne'
      fullPath: '/zycie-codzienne'
      preLoaderRoute: typeof ZycieCodzienneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapie': {
      id: '/terapie'
      path: '/terapie'
      fullPath: '/terapie'
      preLoaderRoute: typeof TerapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spolecznosc': {
      id: '/spolecznosc'
      path: '/spolecznosc'
      fullPath: '/spolecznosc'
      preLoaderRoute: typeof SpolecznoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo-finanse': {
      id: '/prawo-finanse'
      path: '/prawo-finanse'
      fullPath: '/prawo-finanse'
      preLoaderRoute: typeof PrawoFinanseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomoc-kryzysowa': {
      id: '/pomoc-kryzysowa'
      path: '/pomoc-kryzysowa'
      fullPath: '/pomoc-kryzysowa'
      preLoaderRoute: typeof PomocKryzysowaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapy-zycia': {
      id: '/etapy-zycia'
      path: '/etapy-zycia'
      fullPath: '/etapy-zycia'
      preLoaderRoute: typeof EtapyZyciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baza-wiedzy': {
      id: '/baza-wiedzy'
      path: '/baza-wiedzy'
      fullPath: '/baza-wiedzy'
      preLoaderRoute: typeof BazaWiedzyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artykul/$slug': {
      id: '/artykul/$slug'
      path: '/artykul/$slug'
      fullPath: '/artykul/$slug'
      preLoaderRoute: typeof ArtykulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BazaWiedzyRoute: BazaWiedzyRoute,
  EtapyZyciaRoute: EtapyZyciaRoute,
  KalkulatorRoute: KalkulatorRoute,
  KatalogRoute: KatalogRoute,
  KontoRoute: KontoRoute,
  PomocKryzysowaRoute: PomocKryzysowaRoute,
  PrawoFinanseRoute: PrawoFinanseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlownikRoute: SlownikRoute,
  SpolecznoscRoute: SpolecznoscRoute,
  TerapieRoute: TerapieRoute,
  ZycieCodzienneRoute: ZycieCodzienneRoute,
  ArtykulSlugRoute: ArtykulSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
